### PR TITLE
Remove use of rust-musl-builder image from API Proxy build.sh

### LINKED ISSUE #7368: API Proxy module can't be build with included build.sh
## Expected Behavior
Running `./edge-modules/api-proxy-module/build.sh ` should build the module.

## Current Behavior
After running the script it fails to OS Error 13 when trying to create a tmp file to `/opt/rust/rustup`

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Checkout iotedge repo
2. Run `./edge-modules/api-proxy-module/build.sh` from the repository root

### Device Information
* Host OS: WSL 2 Ubuntu 22.04: 
* Architecture: amd64: 

## Additional Information
This is due to build.sh using `ekidd/rust-musl-builder` without a version tag which defaults to `latest` which in turn has had massive changes (remove of ARM support).

### PR DESCRIPTION
**Pull request by nlcamp**
Resolves #7368 

Replaces use of ekidd/rust-musl-builder with cross-platform-rust-build.sh. This fixes errors that occur when build.sh runs (i.e. the OS Error 13 that occurs when attempting to create a tmp file to /opt/rust/rustup).

This change was tested on an ubuntu 20.04 dev machine by setting the ARCH env var to amd64 and running build.sh. This resulted in the azureiotedge-api-proxy image building successfully locally without any errors.

## Azure IoT Edge PR checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines and Best Practices
- [x] I have read the [contribution guidelines](https://github.com/azure/iotedge#contributing).
- [x] Title of the pull request is clear and informative.
- [x] Description of the pull request includes a concise summary of the enhancement or bug fix.

### Testing Guidelines
- [ ] Pull request includes test coverage for the included changes.
- Description of the pull request includes 
	- [ ] concise summary of tests added/modified
	- [ ] local testing done.

### CODE REVIEW

File: edge-modules/api-proxy-module/build.sh [hunk 1]
```diff
@@ -88,7 +88,7 @@ echo ${PROJECT_ROOT}
 
 if [[ "$ARCH" == "amd64" ]]; then
 set +e
-docker run --rm -it -v "${PROJECT_ROOT}":/home/rust/src ekidd/rust-musl-builder cargo build --release --manifest-path /home/rust/src/edge-modules/api-proxy-module/Cargo.toml
+../../scripts/linux/cross-platform-rust-build.sh --os alpine --arch $ARCH --build-path edge-modules/api-proxy-module
```
Comment (damonbarry) [inline edge-modules/api-proxy-module/build.sh:91]: This brings the amd64 path inline with how we already do it for aarch64. What about arm32v7?

**Comment by damonbarry** [comment]
Added @huguesBouvier as a reviewer

**Review by huguesBouvier — APPROVED** [review]
This is fine, I was using this to "manually" build images.

**Comment by samuliHeikkinen** [comment]
Can this be merged?

**Comment by damonbarry** [comment]
> Can this be merged?

Thanks for surfacing this. I'll work on it.
